name: Upload nightly

on:
   workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version of the script
        run: |
          echo "VERSION=$(cat script.ps1 | grep \$Version -m 1 | grep -oP '"\K[^"\047]+(?=["\047])')" >> $GITHUB_ENV
          echo "Found version v${{ env.VERSION }}"

      - name: Update Development Nightly
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'nightly'
          name: 'SpotiX+ Reborn - BETA (v${{ env.VERSION }})'
          prerelease: true
          draft: true
          files: 'script.ps1'
